import { describe, expect, test } from "bun:test";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { adoptProject } from "../src/adopt-project";
import { hashFileContent } from "../src/hashing";
import { readManifest } from "../src/manifest";
import { cleanupTempDir, materializeToTemp } from "../src/materialize";
import { planFeatureSet } from "../src/plan";
import { getCanonicalStarterVersion } from "../src/starter-version";

function createLegacyProject(): string {
  const dir = mkdtempSync(path.join(tmpdir(), "legacy-"));
  // Write minimal GENERATED.md
  const generated = `# GENERATED project
- profile: minimal
- features: (none)
generated by @consulting/generator
`;
  writeFileSync(path.join(dir, "GENERATED.md"), generated);
  // Create a file that would be in baseline to test hash
  const canonical = materializeToTemp(planFeatureSet([], "minimal"));
  try {
    const sample = path.join(canonical, "package.json");
    if (existsSync(sample)) {
      const content = readFileSync(sample, "utf8");
      writeFileSync(path.join(dir, "package.json"), content);
    }
    // Ensure at least package.json exists for comparison
  } finally {
    cleanupTempDir(canonical);
  }
  return dir;
}

describe("adopt", () => {
  test("stores canonical baselineHash not local customized", () => {
    const dir = createLegacyProject();
    // Customize package.json
    const pkgPath = path.join(dir, "package.json");
    const before = JSON.parse(readFileSync(pkgPath, "utf8"));
    (before as Record<string, unknown>).customField = "local";
    writeFileSync(pkgPath, JSON.stringify(before, null, 2));
    const canonical = getCanonicalStarterVersion();
    const result = adoptProject({ project: dir, baseline: canonical });
    expect(existsSync(result.manifestPath)).toBe(true);
    const manifest = readManifest(dir);
    // The stored hash should be canonical, not local customized
    const canonicalDir = materializeToTemp(planFeatureSet([], "minimal"));
    try {
      const canonicalPkg = readFileSync(path.join(canonicalDir, "package.json"), "utf8");
      const canonicalHash = hashFileContent(canonicalPkg);
      const entry = manifest.managedFiles["package.json"];
      expect(entry?.baselineHash).toBe(canonicalHash);
      expect(entry?.strategy).toBe("structured");
    } finally {
      cleanupTempDir(canonicalDir);
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test("unmaterializable baseline fails without manifest", () => {
    const dir = createLegacyProject();
    const badBaseline = "0.10.1";
    if (badBaseline === getCanonicalStarterVersion()) {
      rmSync(dir, { recursive: true, force: true });
      return;
    }
    expect(() => adoptProject({ project: dir, baseline: badBaseline })).toThrow(
      /not materializable/,
    );
    expect(existsSync(path.join(dir, ".api-starter", "manifest.json"))).toBe(false);
    rmSync(dir, { recursive: true, force: true });
  });
});
