import { describe, expect, test } from "bun:test";
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import {
  generateModule,
  parseModuleArgs,
  toPascalCase,
  validateModuleOptions,
} from "../src/create-module";
import { GenerationError } from "../src/errors";

function walkFiles(root: string): string[] {
  const files: string[] = [];
  const walk = (directory: string, relative: string): void => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const nextRelative = relative === "" ? entry.name : `${relative}/${entry.name}`;
      const nextPath = path.join(directory, entry.name);
      if (entry.isDirectory()) {
        walk(nextPath, nextRelative);
      } else {
        files.push(nextRelative);
      }
    }
  };
  walk(root, "");
  return files.sort();
}

function readTree(root: string): Map<string, string> {
  return new Map(
    walkFiles(root).map((relative) => [relative, readFileSync(path.join(root, relative), "utf8")]),
  );
}

function expectedBaseFiles(): string[] {
  return [
    "package.json",
    "src/application/ports.ts",
    "src/application/requests-service.ts",
    "src/domain/requests.entity.ts",
    "src/domain/requests.errors.ts",
    "src/index.ts",
    "tests/requests.test.ts",
  ];
}

function assertGeneratedMarkers(files: Map<string, string>): void {
  for (const [relative, source] of files) {
    expect(source, relative).toContain("generated by @consulting/generator");
    expect(source, relative).toContain("Customize this scaffold");
  }
}

function declaredPackageName(specifier: string): string {
  if (specifier.startsWith("@")) {
    const parts = specifier.split("/");
    return `${parts[0]}/${parts[1]}`;
  }
  return specifier.split("/")[0] ?? specifier;
}

function assertGeneratedReferencesResolve(moduleRoot: string): void {
  const files = readTree(moduleRoot);
  const packageJson = JSON.parse(files.get("package.json") ?? "{}") as {
    dependencies?: Record<string, string>;
  };
  const dependencies = new Set(Object.keys(packageJson.dependencies ?? {}));
  const pascalPlaceholder = "$" + "{pascal}";
  const fieldPlaceholder = "$" + "{field}";

  for (const [relative, source] of files) {
    if (!relative.endsWith(".ts")) continue;
    for (const match of source.matchAll(/from\s+["']([^"']+)["']/g)) {
      const specifier = match[1];
      if (specifier === undefined) continue;
      if (specifier.startsWith(".")) {
        const absolute = path.resolve(path.dirname(path.join(moduleRoot, relative)), specifier);
        const candidates = [absolute, `${absolute}.ts`, path.join(absolute, "index.ts")];
        expect(
          candidates.some((candidate) => existsSync(candidate)),
          `${relative}: ${specifier}`,
        ).toBe(true);
        continue;
      }
      if (specifier.startsWith("node:") || specifier === "bun:test") continue;
      expect(dependencies.has(declaredPackageName(specifier)), `${relative}: ${specifier}`).toBe(
        true,
      );
    }
    expect(source).not.toContain("@consulting/auth");
    expect(source.toLowerCase()).not.toContain("better-auth");
    expect(source).not.toContain(pascalPlaceholder);
    expect(source).not.toContain(fieldPlaceholder);
  }
}

describe("create-module validation", () => {
  test("rejects invalid names and scopes", () => {
    for (const name of ["", "Requests", "two words", "-requests", "requests-"]) {
      expect(() => validateModuleOptions({ name, scope: "global" })).toThrow(GenerationError);
    }
    expect(() =>
      validateModuleOptions({ name: "requests", scope: "workspace" as "global" }),
    ).toThrow(/expected global, user, or tenant/);
    expect(() => parseModuleArgs(["--name=requests"])).toThrow(/missing required --scope/);
    expect(() => parseModuleArgs(["--scope=tenant"])).toThrow(/missing required --name/);
  });

  test("converts kebab-case names to PascalCase", () => {
    expect(toPascalCase("requests")).toBe("Requests");
    expect(toPascalCase("web-hooks")).toBe("WebHooks");
  });
});

describe("create-module output", () => {
  test("tenant CRUD/events/audit emits a scoped, self-contained module", () => {
    const root = mkdtempSync(path.join(tmpdir(), "create-module-tenant-"));
    try {
      const result = generateModule({
        name: "requests",
        scope: "tenant",
        crud: true,
        events: true,
        audit: true,
        out: root,
      });
      const files = readTree(result.modulePath);

      expect([...files.keys()]).toEqual(
        [
          ...expectedBaseFiles(),
          "src/domain/requests.events.ts",
          "src/http/requests.routes.ts",
          "src/http/schemas.ts",
          "src/infrastructure/db.ts",
          "src/infrastructure/requests.mapper.ts",
          "src/infrastructure/requests.repository.ts",
          "src/infrastructure/requests.schema.ts",
        ].sort(),
      );
      assertGeneratedMarkers(files);

      expect(files.get("src/domain/requests.entity.ts")).toContain("organizationId: string");
      expect(files.get("src/application/ports.ts")).toContain(
        "findById(input: { organizationId: string; id: string })",
      );
      expect(files.get("src/application/requests-service.ts")).toContain("organizationId: string");
      expect(files.get("src/http/requests.routes.ts")).toContain("organizationId");
      expect(files.get("src/http/requests.routes.ts")).toContain(
        "@consulting/module-organizations tenant middleware",
      );
      expect(files.get("src/domain/requests.events.ts")).toContain("createRequestsEvent");
      expect(files.get("src/application/requests-service.ts")).toContain(
        'import type { AuditLogger } from "@consulting/audit"',
      );
      expect(files.get("src/application/requests-service.ts")).toContain(
        'resourceType: "requests"',
      );

      const packageJson = JSON.parse(files.get("package.json") ?? "{}") as {
        dependencies: Record<string, string>;
      };
      expect(packageJson.dependencies).toEqual({
        "@consulting/audit": "workspace:*",
        "@consulting/contracts": "workspace:*",
        "@consulting/core": "workspace:*",
        "@hono/standard-validator": "0.2.3",
        "drizzle-orm": "0.45.2",
        hono: "4.12.33",
        "hono-openapi": "1.3.1",
        postgres: "3.4.9",
        zod: "4.4.3",
      });
      assertGeneratedReferencesResolve(result.modulePath);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("global without CRUD emits only domain/application files and no optional dependencies", () => {
    const root = mkdtempSync(path.join(tmpdir(), "create-module-global-"));
    try {
      const result = generateModule({ name: "reports", scope: "global", out: root });
      const files = readTree(result.modulePath);
      const expected = expectedBaseFiles().map((file) => file.replaceAll("requests", "reports"));

      expect([...files.keys()]).toEqual(expected.sort());
      expect(files.get("package.json")).toContain('"dependencies": {}');
      expect(files.has("src/infrastructure/db.ts")).toBe(false);
      expect(files.has("src/http/schemas.ts")).toBe(false);
      expect(files.has("src/domain/reports.events.ts")).toBe(false);
      assertGeneratedMarkers(files);
      assertGeneratedReferencesResolve(result.modulePath);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("user CRUD carries userId through the entity, repository, service, and schema", () => {
    const root = mkdtempSync(path.join(tmpdir(), "create-module-user-"));
    try {
      const result = generateModule({ name: "profiles", scope: "user", crud: true, out: root });
      const files = readTree(result.modulePath);
      for (const relative of [
        "src/domain/profiles.entity.ts",
        "src/application/ports.ts",
        "src/application/profiles-service.ts",
        "src/infrastructure/profiles.repository.ts",
        "src/infrastructure/profiles.schema.ts",
      ]) {
        expect(files.get(relative), relative).toContain("userId");
      }
      expect(files.get("src/infrastructure/profiles.schema.ts")).toContain("user_id");
      expect(files.has("src/domain/profiles.events.ts")).toBe(false);
      assertGeneratedReferencesResolve(result.modulePath);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("flags independently control optional files and imports", () => {
    const root = mkdtempSync(path.join(tmpdir(), "create-module-flags-"));
    try {
      const events = generateModule({
        name: "event-log",
        scope: "global",
        events: true,
        out: root,
      });
      expect(existsSync(path.join(events.modulePath, "src/domain/event-log.events.ts"))).toBe(true);
      expect(existsSync(path.join(events.modulePath, "src/http"))).toBe(false);
      expect(existsSync(path.join(events.modulePath, "src/infrastructure"))).toBe(false);

      const audit = generateModule({
        name: "audit-log",
        scope: "global",
        crud: true,
        audit: true,
        out: root,
      });
      expect(existsSync(path.join(audit.modulePath, "src/domain/audit-log.events.ts"))).toBe(false);
      expect(
        readFileSync(path.join(audit.modulePath, "src/application/audit-log-service.ts"), "utf8"),
      ).toContain("AuditLogger");

      const crud = generateModule({ name: "tasks", scope: "global", crud: true, out: root });
      expect(existsSync(path.join(crud.modulePath, "src/http/tasks.routes.ts"))).toBe(true);
      expect(existsSync(path.join(crud.modulePath, "src/infrastructure/tasks.repository.ts"))).toBe(
        true,
      );
      expect(existsSync(path.join(crud.modulePath, "src/domain/tasks.events.ts"))).toBe(false);
      const packageJson = JSON.parse(
        readFileSync(path.join(crud.modulePath, "package.json"), "utf8"),
      ) as { dependencies: Record<string, string> };
      expect(packageJson.dependencies["@consulting/audit"]).toBeUndefined();
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe("create-module destination safety", () => {
  test("fails safely on an existing module and force recreates only that target", () => {
    const root = mkdtempSync(path.join(tmpdir(), "create-module-safe-"));
    try {
      const first = generateModule({ name: "requests", scope: "global", out: root });
      const sibling = path.join(root, "keep.txt");
      writeFileSync(sibling, "keep me", "utf8");
      const sentinel = path.join(first.modulePath, "sentinel.txt");
      writeFileSync(sentinel, "must be removed by force", "utf8");

      expect(() => generateModule({ name: "requests", scope: "global", out: root })).toThrow(
        /already exists.*--force/,
      );
      expect(existsSync(sentinel)).toBe(true);
      expect(readFileSync(sibling, "utf8")).toBe("keep me");

      generateModule({ name: "requests", scope: "global", out: root, force: true });
      expect(existsSync(sentinel)).toBe(false);
      expect(readFileSync(sibling, "utf8")).toBe("keep me");
      expect(existsSync(path.join(root, "requests", "src/index.ts"))).toBe(true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
