import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

import { repositoryRoot } from "./create-project";
import { GenerationError } from "./errors";
import { getFeature } from "./features";
import { hashFileContent } from "./hashing";
import { readManifest, writeManifest } from "./manifest";
import { filterMigrationJournal, snapshotNameFor } from "./migrations";
import { PERSISTENCE_MODULES, type ProjectPlan, planFeatureSet } from "./plan";
import { getProfile } from "./profiles";
import {
  rewriteAppPackageJson,
  rewriteConfigEnv,
  rewriteDockerCompose,
  rewriteDrizzleConfig,
  rewriteEnvExample,
  rewriteRootPackageJson,
} from "./prune";
import { selectTemplates } from "./templates";
import { validateFeatureSet } from "./validate";

const USAGE =
  "usage: bun generator/src/add-feature.ts --feature=<id> --project=<dir> [--with-requires] [--force]";
const GENERATOR_MARKER = "generated by @consulting/generator";
const GENERATED_PROJECT_MARKER = "# GENERATED project";
const FEATURE_PLAN_MARKER = "<!-- generated by @consulting/generator -->";

const TENANCY_WARNING =
  "WARNING: adding multi-tenancy to an existing project requires a manual data migration. No data was modified and this plan was not executed.";

export const TENANCY_MIGRATION_STEPS = [
  "Review existing tables and identify tenant-scoped resources.",
  "Add organization_id to tenant resources.",
  "Backfill organization and membership data.",
  "Add tenant indexes and constraints.",
  "Review IDOR and authorization boundaries.",
  "Run migrations and tenant-isolation tests.",
] as const;

export interface TenancyMigrationPlan {
  executed: false;
  status: "not-executed";
  steps: readonly string[];
}

export interface GeneratedManifest {
  profile: string;
  features: string[];
}

export type AddFeatureIssueKind = "missing-requirement" | "conflict" | "unknown-feature" | "safety";

export interface AddFeatureIssue {
  kind: AddFeatureIssueKind;
  feature: string;
  message: string;
  requirement?: string;
}

export interface AddFeatureFailure {
  feature: string;
  errors: AddFeatureIssue[];
  dryRun: boolean;
}

export class FeatureAdditionError extends GenerationError {
  readonly result: AddFeatureFailure;

  constructor(message: string, result: AddFeatureFailure) {
    super(message);
    this.name = "FeatureAdditionError";
    this.result = result;
  }
}

export interface AddFeatureOptions {
  feature: string;
  project: string;
  withRequires?: boolean;
  force?: boolean;
  dryRun?: boolean;
  /** Test seam for applying a plan from a different source tree. */
  sourceRoot?: string;
}

export interface AddFeatureResult {
  feature: string;
  addedFeatures: string[];
  warning?: string;
  migrationPlan?: TenancyMigrationPlan;
  errors?: AddFeatureIssue[];
  copiedPaths: string[];
  rewrittenPaths: string[];
  status: "added" | "already-enabled";
  dryRun: boolean;
}

interface FileOperation {
  kind: "copy" | "rewrite";
  relativePath: string;
  sourcePath?: string;
  content?: string;
}

export interface ResourceApplicationResult {
  copiedPaths: string[];
  rewrittenPaths: string[];
}

function normalizeFeatureId(id: string): string {
  return id.trim() === "multitenancy" ? "tenancy" : id.trim();
}

function normalizeFeatureList(features: readonly string[]): string[] {
  const normalized: string[] = [];
  const seen = new Set<string>();
  for (const raw of features) {
    const id = normalizeFeatureId(raw);
    if (id === "") {
      throw new GenerationError("generated manifest contains an empty feature id");
    }
    getFeature(id);
    if (seen.has(id)) {
      throw new GenerationError(`generated manifest contains duplicate feature "${id}"`);
    }
    seen.add(id);
    normalized.push(id);
  }
  return normalized;
}

/**
 * Reads only the explicit marker fields. A missing or malformed marker is a
 * hard failure: add:feature never guesses the state of an arbitrary repo.
 */
export function readGeneratedManifest(source: string): GeneratedManifest {
  if (!source.includes(GENERATED_PROJECT_MARKER)) {
    throw new GenerationError(
      "project is not a generated project: GENERATED.md is missing the '# GENERATED project' marker",
    );
  }

  const profile = source.match(/^- profile:\s*([^\r\n]+?)\s*$/m)?.[1]?.trim();
  const featuresLine = source.match(/^- features:\s*([^\r\n]+?)\s*$/m)?.[1]?.trim();
  if (profile === undefined || profile === "") {
    throw new GenerationError("GENERATED.md is malformed: missing '- profile:'");
  }
  getProfile(profile);
  if (featuresLine === undefined || featuresLine === "") {
    throw new GenerationError("GENERATED.md is malformed: missing '- features:'");
  }

  const rawFeatures = featuresLine === "(none)" ? [] : featuresLine.split(",");
  return { profile, features: normalizeFeatureList(rawFeatures) };
}

/**
 * Updates only the feature line and appends an audit-style addition section.
 * Existing notes and the generated timestamp are left byte-for-byte intact.
 */
export function updateGeneratedManifest(
  source: string,
  features: readonly string[],
  warning?: string,
): string {
  const current = readGeneratedManifest(source);
  const normalized = normalizeFeatureList(features);
  const featureLine = normalized.length === 0 ? "(none)" : normalized.join(", ");
  const featurePattern = /^- features:\s*[^\r\n]*$/m;
  if (!featurePattern.test(source)) {
    throw new GenerationError("GENERATED.md is malformed: missing '- features:'");
  }

  let result = source.replace(featurePattern, `- features: ${featureLine}`);
  const added = normalized.filter((feature) => !current.features.includes(feature));
  const sections: string[] = [];
  if (added.length > 0) {
    sections.push(["Added features:", ...added.map((feature) => `- ${feature}`)].join("\n"));
  }
  if (warning !== undefined) {
    sections.push(["WARNING:", warning].join("\n"));
  }
  if (sections.length > 0) {
    result = `${result.replace(/\s+$/, "")}\n\n${sections.join("\n\n")}\n`;
  }
  return result;
}

/**
 * Returns newly selected features in deterministic dependency-first order.
 * Existing features are omitted, so the return value is directly suitable for
 * AddFeatureResult.addedFeatures.
 */
export function resolveFeatureClosure(
  feature: string,
  currentFeatures: readonly string[],
  withRequires: boolean,
): string[] {
  const requested = normalizeFeatureId(feature);
  getFeature(requested);
  const current = new Set(currentFeatures.map(normalizeFeatureId));
  if (current.has(requested)) {
    return [];
  }

  const result: string[] = [];
  const visiting = new Set<string>();
  const visited = new Set<string>();
  const visit = (id: string): void => {
    if (current.has(id) || visited.has(id)) {
      return;
    }
    if (visiting.has(id)) {
      throw new GenerationError(`feature requirements contain a cycle at "${id}"`);
    }
    visiting.add(id);
    if (withRequires) {
      for (const requirement of getFeature(id).requires) {
        visit(requirement);
      }
    }
    visiting.delete(id);
    visited.add(id);
    result.push(id);
  };
  visit(requested);
  return result;
}

/** Computes a pure plan for a feature set that is not necessarily a profile. */
export function featurePlanFor(features: readonly string[]): ProjectPlan {
  return planFeatureSet(normalizeFeatureList(features));
}

function tenancyMigrationPlan(): TenancyMigrationPlan {
  return {
    executed: false,
    status: "not-executed",
    steps: [...TENANCY_MIGRATION_STEPS],
  };
}

function isGeneratedContent(source: string): boolean {
  return (
    source.includes(GENERATOR_MARKER) ||
    source.includes(GENERATED_PROJECT_MARKER) ||
    source.includes(FEATURE_PLAN_MARKER)
  );
}

function assertSourceDirectory(sourcePath: string): void {
  if (!existsSync(sourcePath) || !statSync(sourcePath).isDirectory()) {
    throw new GenerationError(`generator resource directory is missing: ${sourcePath}`);
  }
}

function sourceFiles(root: string, relative = ""): string[] {
  const directory = path.join(root, relative);
  const entries = readdirSync(directory, { withFileTypes: true }).sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  const result: string[] = [];
  for (const entry of entries) {
    if ([".git", ".codegraph", "coverage", "node_modules"].includes(entry.name)) {
      continue;
    }
    const child = relative === "" ? entry.name : path.join(relative, entry.name);
    if (entry.isDirectory()) {
      result.push(...sourceFiles(root, child));
    } else if (entry.isFile()) {
      result.push(child);
    }
  }
  return result;
}

function addCopyOperation(
  operations: FileOperation[],
  sourcePath: string,
  targetPath: string,
  relative: string,
  force: boolean,
): void {
  if (!existsSync(sourcePath)) {
    throw new GenerationError(`generator resource is missing: ${sourcePath}`);
  }
  const source = readFileSync(sourcePath);
  if (existsSync(targetPath)) {
    if (statSync(targetPath).isDirectory()) {
      throw new GenerationError(`cannot overwrite directory with generated file: ${targetPath}`);
    }
    const current = readFileSync(targetPath);
    if (Buffer.compare(source, current) === 0) {
      return;
    }
    if (!force && !isGeneratedContent(current.toString("utf8"))) {
      throw new GenerationError(
        `refusing to overwrite custom file ${targetPath}; pass --force to update only this feature's resources`,
      );
    }
  }
  operations.push({ kind: "copy", relativePath: relative, sourcePath });
}

function addTreeCopyOperations(
  operations: FileOperation[],
  sourceRoot: string,
  projectRoot: string,
  relativeDirectory: string,
  force: boolean,
): void {
  const sourceDirectory = path.join(sourceRoot, relativeDirectory);
  assertSourceDirectory(sourceDirectory);
  for (const file of sourceFiles(sourceDirectory)) {
    const sourcePath = path.join(sourceDirectory, file);
    const relative = path.posix.join(relativeDirectory.split(path.sep).join("/"), file);
    addCopyOperation(operations, sourcePath, path.join(projectRoot, relative), relative, force);
  }
}

function addRewriteOperation(
  operations: FileOperation[],
  projectRoot: string,
  relative: string,
  expected: string,
  next: string,
  force: boolean,
): void {
  if (expected === next) {
    return;
  }
  const targetPath = path.join(projectRoot, relative);
  if (existsSync(targetPath)) {
    if (statSync(targetPath).isDirectory()) {
      throw new GenerationError(`cannot overwrite directory with generated file: ${targetPath}`);
    }
    const current = readFileSync(targetPath, "utf8");
    if (current !== expected && !force && !isGeneratedContent(current)) {
      throw new GenerationError(
        `refusing to overwrite custom file ${targetPath}; pass --force to apply the feature plan`,
      );
    }
    if (current === next) {
      return;
    }
  }
  operations.push({ kind: "rewrite", relativePath: relative, content: next });
}

function featureResourceNames(featureIds: readonly string[]): {
  modules: string[];
  packages: string[];
} {
  const modules = new Set<string>();
  const packages = new Set<string>();
  for (const rawId of featureIds) {
    const id = normalizeFeatureId(rawId);
    const feature = getFeature(id);
    for (const moduleName of feature.modules) {
      modules.add(moduleName);
    }
    for (const packageName of feature.packages) {
      packages.add(packageName);
    }
    if (id === "persistence") {
      for (const moduleName of PERSISTENCE_MODULES) {
        modules.add(moduleName);
      }
    }
  }
  return { modules: [...modules].sort(), packages: [...packages].sort() };
}

function readProjectManifest(projectRoot: string): GeneratedManifest {
  const manifestPath = path.join(projectRoot, "GENERATED.md");
  if (!existsSync(manifestPath) || !statSync(manifestPath).isFile()) {
    throw new GenerationError(
      `project ${projectRoot} is not generated: GENERATED.md is missing; refusing to mutate it`,
    );
  }
  return readGeneratedManifest(readFileSync(manifestPath, "utf8"));
}

function applyOperations(
  projectRoot: string,
  operations: readonly FileOperation[],
  dryRun: boolean,
): ResourceApplicationResult {
  if (!dryRun) {
    for (const operation of operations) {
      const targetPath = path.join(projectRoot, operation.relativePath);
      mkdirSync(path.dirname(targetPath), { recursive: true });
      if (operation.kind === "copy") {
        copyFileSync(operation.sourcePath as string, targetPath);
      } else {
        writeFileSync(targetPath, operation.content as string);
      }
    }
  }

  return {
    copiedPaths: operations
      .filter((operation) => operation.kind === "copy")
      .map((operation) => operation.relativePath)
      .sort(),
    rewrittenPaths: operations
      .filter((operation) => operation.kind === "rewrite")
      .map((operation) => operation.relativePath)
      .sort(),
  };
}

/**
 * Copies newly selected feature resources and applies the canonical
 * composition rewrites. All safety checks happen before the first write.
 */
export function copyFeatureResources(
  sourceRoot: string,
  projectRoot: string,
  featureIds: readonly string[],
  plan: ProjectPlan,
  options: { force?: boolean; dryRun?: boolean } = {},
): ResourceApplicationResult {
  const source = path.resolve(sourceRoot);
  const project = path.resolve(projectRoot);
  if (source === project) {
    throw new GenerationError(
      "refusing to add a feature to the generator source repository itself",
    );
  }
  assertSourceDirectory(source);
  assertSourceDirectory(project);

  const manifest = readProjectManifest(project);
  const currentPlan = planFeatureSet(manifest.features, manifest.profile);
  const force = options.force ?? false;
  const operations: FileOperation[] = [];
  const resources = featureResourceNames(featureIds);

  for (const moduleName of resources.modules) {
    addTreeCopyOperations(operations, source, project, `modules/${moduleName}`, force);
  }
  for (const packageName of resources.packages) {
    addTreeCopyOperations(operations, source, project, `packages/${packageName}`, force);
  }
  if (featureIds.map(normalizeFeatureId).includes("persistence")) {
    addTreeCopyOperations(operations, source, project, "scripts/db", force);
  }
  if (featureIds.map(normalizeFeatureId).includes("tenancy")) {
    // Standalone outbox worker (compose profile `worker`): its entrypoint is
    // tenancy-owned tooling, pruned from projects without organizations.
    addCopyOperation(
      operations,
      path.join(source, "scripts", "worker.ts"),
      path.join(project, "scripts", "worker.ts"),
      "scripts/worker.ts",
      force,
    );
  }

  const currentMigrations = new Set(currentPlan.keepMigrations);
  for (const migration of plan.keepMigrations) {
    if (currentMigrations.has(migration)) {
      continue;
    }
    addCopyOperation(
      operations,
      path.join(source, "migrations", migration),
      path.join(project, "migrations", migration),
      `migrations/${migration}`,
      force,
    );
    addCopyOperation(
      operations,
      path.join(source, "migrations", "meta", snapshotNameFor(migration)),
      path.join(project, "migrations", "meta", snapshotNameFor(migration)),
      `migrations/meta/${snapshotNameFor(migration)}`,
      force,
    );
  }

  const currentTests = new Set(currentPlan.keepAppTests);
  for (const testFile of plan.keepAppTests) {
    if (currentTests.has(testFile)) {
      continue;
    }
    addCopyOperation(
      operations,
      path.join(source, "apps", "api", "tests", testFile),
      path.join(project, "apps", "api", "tests", testFile),
      `apps/api/tests/${testFile}`,
      force,
    );
  }

  if (plan.features.includes("authorization") && !currentPlan.features.includes("authorization")) {
    addCopyOperation(
      operations,
      path.join(source, "apps", "api", "src", "http", "authorization.ts"),
      path.join(project, "apps", "api", "src", "http", "authorization.ts"),
      "apps/api/src/http/authorization.ts",
      force,
    );
  }

  const sourceTemplates = path.join(source, "generator", "templates", "app");
  const currentTemplates = selectTemplates(currentPlan);
  const nextTemplates = selectTemplates(plan);
  const templateTargets = [
    ["app", currentTemplates.app, nextTemplates.app, "apps/api/src/app.ts"],
    ["routes", currentTemplates.routes, nextTemplates.routes, "apps/api/src/routes.ts"],
  ] as const;
  for (const [, currentTemplate, nextTemplate, target] of templateTargets) {
    const expected = readFileSync(path.join(sourceTemplates, currentTemplate), "utf8");
    const next = readFileSync(path.join(sourceTemplates, nextTemplate), "utf8");
    addRewriteOperation(operations, project, target, expected, next, force);
  }

  const rewriteInputs = [
    {
      relative: "package.json",
      rewrite: rewriteRootPackageJson,
    },
    {
      relative: "apps/api/package.json",
      rewrite: rewriteAppPackageJson,
    },
    {
      relative: "drizzle.config.ts",
      rewrite: rewriteDrizzleConfig,
    },
    {
      relative: ".env.example",
      rewrite: rewriteEnvExample,
    },
    {
      relative: "packages/config/src/env.ts",
      rewrite: rewriteConfigEnv,
    },
    {
      relative: "docker-compose.yml",
      rewrite: rewriteDockerCompose,
    },
  ] as const;
  for (const input of rewriteInputs) {
    const sourceText = readFileSync(path.join(source, input.relative), "utf8");
    const expected = input.rewrite(sourceText, currentPlan);
    const next = input.rewrite(sourceText, plan);
    addRewriteOperation(operations, project, input.relative, expected, next, force);
  }

  const journalSource = readFileSync(
    path.join(source, "migrations", "meta", "_journal.json"),
    "utf8",
  );
  addRewriteOperation(
    operations,
    project,
    "migrations/meta/_journal.json",
    filterMigrationJournal(journalSource, currentPlan.keepMigrations),
    filterMigrationJournal(journalSource, plan.keepMigrations),
    force,
  );

  return applyOperations(project, operations, options.dryRun ?? false);
}

function renderFeaturePlan(
  addedFeatures: readonly string[],
  plan: ProjectPlan,
  currentPlan: ProjectPlan,
  warning: string | undefined,
  migrationPlan: TenancyMigrationPlan | undefined,
): string {
  const newMigrations = plan.keepMigrations.filter(
    (migration) => !currentPlan.keepMigrations.includes(migration),
  );
  const lines = [
    FEATURE_PLAN_MARKER,
    "# Feature Plan",
    "",
    `Added features: ${addedFeatures.join(", ")}`,
    `Current features: ${plan.features.length === 0 ? "(none)" : plan.features.join(", ")}`,
    "",
    "Migrations to apply:",
    ...(newMigrations.length === 0
      ? ["- (none)"]
      : newMigrations.map((migration) => `- ${migration}`)),
  ];
  if (warning !== undefined && migrationPlan !== undefined) {
    lines.push(
      "",
      "## Tenancy warning",
      warning,
      "",
      "Migration plan (not executed):",
      ...migrationPlan.steps.map((step) => `- ${step}`),
    );
  }
  lines.push(
    "",
    "Next steps:",
    "- Review this plan before applying migrations.",
    "- Run `bun install` to refresh workspace dependencies.",
  );
  return `${lines.join("\n")}\n`;
}

function assertDocumentationWritable(
  projectRoot: string,
  relative: string,
  next: string,
  force: boolean,
): void {
  const target = path.join(projectRoot, relative);
  if (!existsSync(target)) {
    return;
  }
  if (statSync(target).isDirectory()) {
    throw new GenerationError(`cannot overwrite directory with generated file: ${target}`);
  }
  const current = readFileSync(target, "utf8");
  if (current !== next && !force && !isGeneratedContent(current)) {
    throw new GenerationError(
      `refusing to overwrite custom file ${target}; pass --force to update the generated feature plan`,
    );
  }
}

function failure(
  feature: string,
  message: string,
  errors: AddFeatureIssue[],
  dryRun: boolean,
): never {
  throw new FeatureAdditionError(message, { feature, errors, dryRun });
}

/** Applies one feature addition to an existing generated project. */
export function addFeature(options: AddFeatureOptions): AddFeatureResult {
  const feature = normalizeFeatureId(options.feature);
  const sourceRoot = path.resolve(options.sourceRoot ?? repositoryRoot());
  const projectRoot = path.resolve(options.project);
  const dryRun = options.dryRun ?? false;

  if (feature === "") {
    failure(
      "",
      "--feature must not be empty",
      [{ kind: "unknown-feature", feature: "", message: "--feature must not be empty" }],
      dryRun,
    );
  }
  getFeature(feature);
  if (!existsSync(projectRoot) || !statSync(projectRoot).isDirectory()) {
    failure(
      feature,
      `project directory does not exist or is not a directory: ${projectRoot}`,
      [{ kind: "safety", feature, message: `invalid project directory ${projectRoot}` }],
      dryRun,
    );
  }
  if (sourceRoot === projectRoot) {
    failure(
      feature,
      "refusing to mutate the generator source repository itself",
      [{ kind: "safety", feature, message: "project and generator source are the same directory" }],
      dryRun,
    );
  }

  const manifestPath = path.join(projectRoot, "GENERATED.md");
  if (!existsSync(manifestPath)) {
    failure(
      feature,
      `project ${projectRoot} is not generated: GENERATED.md is missing`,
      [{ kind: "safety", feature, message: "missing generated project marker" }],
      dryRun,
    );
  }
  const manifestSource = readFileSync(manifestPath, "utf8");
  const manifest = readGeneratedManifest(manifestSource);
  const currentFeatures = manifest.features;
  const currentIssues = validateFeatureSet(currentFeatures);
  if (currentIssues.length > 0) {
    failure(
      feature,
      `generated manifest feature set is invalid: ${currentIssues
        .map((issue) => issue.message)
        .join("; ")}`,
      currentIssues.map((issue) => ({
        kind:
          issue.kind === "unknown-feature"
            ? "unknown-feature"
            : issue.kind === "missing-requirement"
              ? "missing-requirement"
              : "conflict",
        feature: issue.feature,
        message: issue.message,
      })),
      dryRun,
    );
  }

  if (currentFeatures.includes(feature)) {
    return {
      feature,
      addedFeatures: [],
      copiedPaths: [],
      rewrittenPaths: [],
      status: "already-enabled",
      dryRun,
    };
  }

  const withRequires = options.withRequires ?? false;
  const addedFeatures = resolveFeatureClosure(feature, currentFeatures, withRequires);
  const resultingFeatures = [...currentFeatures, ...addedFeatures];
  const issues = validateFeatureSet(resultingFeatures);
  if (issues.length > 0) {
    const missing = issues.filter((issue) => issue.kind === "missing-requirement");
    const mapped = missing.map((issue) => {
      const requirement = issue.message.match(/requires "([^"]+)"/)?.[1];
      return {
        kind: "missing-requirement" as const,
        feature: issue.feature,
        message: issue.message,
        ...(requirement === undefined ? {} : { requirement }),
      };
    });
    if (missing.length > 0 && !withRequires) {
      const requirementList = missing
        .map((issue) => issue.message.replace(/^Feature /, ""))
        .join("; ");
      failure(
        feature,
        `cannot add "${feature}": missing requirements: ${requirementList}; add them first or use --with-requires`,
        mapped,
        dryRun,
      );
    }
    failure(
      feature,
      `cannot add "${feature}": ${issues.map((issue) => issue.message).join("; ")}`,
      issues.map((issue) => ({
        kind: issue.kind === "unknown-feature" ? "unknown-feature" : "conflict",
        feature: issue.feature,
        message: issue.message,
      })),
      dryRun,
    );
  }

  const currentPlan = planFeatureSet(currentFeatures, manifest.profile);
  const plan = planFeatureSet(resultingFeatures, manifest.profile);
  const tenancyAdded = addedFeatures.includes("tenancy");
  const warning = tenancyAdded ? TENANCY_WARNING : undefined;
  const migrationPlan = tenancyAdded ? tenancyMigrationPlan() : undefined;
  const nextManifest = updateGeneratedManifest(manifestSource, resultingFeatures, warning);
  const nextFeaturePlan = renderFeaturePlan(
    addedFeatures,
    plan,
    currentPlan,
    warning,
    migrationPlan,
  );

  assertDocumentationWritable(projectRoot, "GENERATED.md", nextManifest, options.force ?? false);
  assertDocumentationWritable(
    projectRoot,
    "FEATURE_PLAN.md",
    nextFeaturePlan,
    options.force ?? false,
  );

  const resources = copyFeatureResources(sourceRoot, projectRoot, addedFeatures, plan, {
    ...(options.force === undefined ? {} : { force: options.force }),
    dryRun,
  });
  const rewrittenPaths = new Set(resources.rewrittenPaths);
  const manifestChanged = manifestSource !== nextManifest;
  const featurePlanPath = path.join(projectRoot, "FEATURE_PLAN.md");
  const featurePlanChanged =
    !existsSync(featurePlanPath) || readFileSync(featurePlanPath, "utf8") !== nextFeaturePlan;
  if (manifestChanged) {
    rewrittenPaths.add("GENERATED.md");
  }
  if (featurePlanChanged) {
    rewrittenPaths.add("FEATURE_PLAN.md");
  }
  if (!dryRun) {
    if (manifestChanged) {
      writeFileSync(manifestPath, nextManifest);
    }
    if (featurePlanChanged) {
      writeFileSync(featurePlanPath, nextFeaturePlan);
    }
  }

  if (!dryRun) {
    try {
      const existingManifest = readManifest(projectRoot);
      const now = new Date().toISOString();
      const updatedManagedFiles: Record<string, { baselineHash: string; strategy: string }> = {
        ...existingManifest.managedFiles,
      };
      const allPaths = [...resources.copiedPaths, ...resources.rewrittenPaths];
      for (const rel of allPaths) {
        const targetPath = path.join(projectRoot, rel);
        if (existsSync(targetPath) && !statSync(targetPath).isDirectory()) {
          try {
            const content = readFileSync(targetPath, "utf8");
            const baselineHash = hashFileContent(content);
            const existing = existingManifest.managedFiles[rel];
            const strategy =
              existing?.strategy ??
              (rel === "package.json" ||
              rel === "apps/api/package.json" ||
              rel === "tsconfig.json" ||
              rel === ".env.example" ||
              rel === "drizzle.config.ts" ||
              rel === "docker-compose.yml" ||
              rel === "packages/config/src/env.ts"
                ? "structured"
                : "managed");
            updatedManagedFiles[rel] = { baselineHash, strategy: strategy as never };
          } catch {
            // ignore binary or unreadable
          }
        }
      }
      const updatedManifestData = {
        ...existingManifest,
        generation: {
          ...existingManifest.generation,
          features: [...resultingFeatures].sort(),
          updatedAt: now,
        },
        managedFiles: Object.fromEntries(
          Object.entries(updatedManagedFiles).sort(([a], [b]) => a.localeCompare(b)),
        ),
      };
      writeManifest(projectRoot, updatedManifestData as never);
    } catch {
      const legacyManifestPath = path.join(projectRoot, ".api-starter", "manifest.json");
      if (!existsSync(legacyManifestPath)) {
        const genPath = path.join(projectRoot, "GENERATED.md");
        if (existsSync(genPath)) {
          console.warn(
            `⚠ No manifest found at ${legacyManifestPath}; found legacy GENERATED.md. Run bun run generator:adopt -- --project=${projectRoot} --baseline=<version> to migrate.`,
          );
        }
      }
    }
  }

  return {
    feature,
    addedFeatures,
    ...(warning === undefined ? {} : { warning }),
    ...(migrationPlan === undefined ? {} : { migrationPlan }),
    copiedPaths: resources.copiedPaths,
    rewrittenPaths: [...rewrittenPaths].sort(),
    status: "added",
    dryRun,
  };
}

export function parseAddFeatureArgs(args: readonly string[]): AddFeatureOptions {
  let feature: string | undefined;
  let project: string | undefined;
  let positionalFeature: string | undefined;
  let withRequires = false;
  let force = false;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === undefined || arg === "--") {
      continue;
    }
    if (arg === "--with-requires") {
      withRequires = true;
      continue;
    }
    if (arg === "--force") {
      force = true;
      continue;
    }
    if (arg === "--feature" || arg.startsWith("--feature=")) {
      feature = arg === "--feature" ? args[++index] : arg.slice("--feature=".length);
      continue;
    }
    if (arg === "--project" || arg.startsWith("--project=")) {
      project = arg === "--project" ? args[++index] : arg.slice("--project=".length);
      continue;
    }
    if (arg.startsWith("--")) {
      throw new GenerationError(`unknown argument "${arg}"`);
    }
    if (positionalFeature === undefined) {
      positionalFeature = arg;
      continue;
    }
    throw new GenerationError(`unknown argument "${arg}"`);
  }

  feature ??= positionalFeature;
  if (feature === undefined || feature === "") {
    throw new GenerationError(`--feature is required\n${USAGE}`);
  }
  if (project === undefined || project === "") {
    throw new GenerationError(`--project is required\n${USAGE}`);
  }
  return { feature, project, withRequires, force };
}

function printSummary(result: AddFeatureResult): void {
  if (result.status === "already-enabled") {
    console.log(`feature "${result.feature}" is already enabled; no files changed`);
    return;
  }
  console.log(`added: ${result.addedFeatures.join(", ")}`);
  console.log(`copied: ${result.copiedPaths.length}; rewritten: ${result.rewrittenPaths.length}`);
  if (result.warning !== undefined) {
    console.warn(result.warning);
    console.warn("migration plan: not executed; review FEATURE_PLAN.md");
  }
  console.log("next step: bun install");
}

export function main(): void {
  try {
    const result = addFeature(parseAddFeatureArgs(process.argv.slice(2)));
    printSummary(result);
  } catch (error) {
    if (error instanceof FeatureAdditionError) {
      console.error(`error: ${error.message}`);
      for (const issue of error.result.errors) {
        console.error(`  [${issue.kind}] ${issue.message}`);
      }
    } else if (error instanceof Error) {
      console.error(`error: ${error.message}`);
    } else {
      console.error("error: feature addition failed");
    }
    process.exitCode = 1;
  }
}

if (import.meta.main) {
  main();
}
