import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";

import { GenerationError } from "./errors";

export type ModuleScope = "global" | "user" | "tenant";

export interface CreateModuleOptions {
  name: string;
  scope: ModuleScope;
  crud?: boolean;
  events?: boolean;
  audit?: boolean;
  out?: string;
  force?: boolean;
}

interface ResolvedModuleOptions {
  name: string;
  scope: ModuleScope;
  crud: boolean;
  events: boolean;
  audit: boolean;
  out: string;
  force: boolean;
}

export interface ModuleGenerationResult {
  modulePath: string;
  files: string[];
}

export const GENERATED_MARKER = "// generated by @consulting/generator — do not edit by hand";
const CUSTOMIZATION_NOTE =
  "// Customize this scaffold in a follow-up change; do not edit generated files in place.";
const MODULE_NAME_PATTERN = /^[a-z][a-z0-9-]*$/;
const SCOPES = ["global", "user", "tenant"] as const;

function isModuleScope(value: string): value is ModuleScope {
  return (SCOPES as readonly string[]).includes(value);
}

/** Converts kebab-case names to PascalCase (`web-hooks` -> `WebHooks`). */
export function toPascalCase(value: string): string {
  return value
    .split("-")
    .map((segment) => `${segment.charAt(0).toUpperCase()}${segment.slice(1)}`)
    .join("");
}

function toCamelCase(value: string): string {
  const pascal = toPascalCase(value);
  return `${pascal.charAt(0).toLowerCase()}${pascal.slice(1)}`;
}

/** Returns the self-contained PostgreSQL table name for a module name. */
export function tableNameFor(value: string): string {
  const snake = value.replaceAll("-", "_");
  if (snake.endsWith("s")) {
    return snake;
  }
  if (snake.endsWith("y")) {
    return `${snake.slice(0, -1)}ies`;
  }
  if (/(x|ch|sh)$/.test(snake)) {
    return `${snake}es`;
  }
  return `${snake}s`;
}

/** Validates a module name without touching the filesystem. */
export function validateModuleName(name: string): void {
  if (!MODULE_NAME_PATTERN.test(name) || name.endsWith("-") || name.includes("--")) {
    throw new GenerationError(
      `invalid module name "${name}": expected kebab-case matching /^[a-z][a-z0-9-]*$/ without empty segments`,
    );
  }
}

/** Validates and fills defaults for programmatic generator calls. */
export function validateModuleOptions(options: CreateModuleOptions): ResolvedModuleOptions {
  if (typeof options.name !== "string" || options.name.length === 0) {
    throw new GenerationError("missing required --name");
  }
  validateModuleName(options.name);

  if (typeof options.scope !== "string" || !isModuleScope(options.scope)) {
    throw new GenerationError(
      `invalid scope "${String(options.scope)}": expected global, user, or tenant`,
    );
  }

  const out = options.out ?? "modules";
  if (typeof out !== "string" || out.trim() === "") {
    throw new GenerationError("--out must not be empty");
  }

  return {
    name: options.name,
    scope: options.scope,
    crud: options.crud ?? false,
    events: options.events ?? false,
    audit: options.audit ?? false,
    out,
    force: options.force ?? false,
  };
}

function readOptionValue(
  args: readonly string[],
  index: number,
  flag: string,
  inlineValue: string | undefined,
): { value: string; nextIndex: number } {
  if (inlineValue !== undefined) {
    return { value: inlineValue, nextIndex: index };
  }
  const value = args[index + 1];
  if (value === undefined || value.startsWith("--")) {
    throw new GenerationError(`missing value for ${flag}`);
  }
  return { value, nextIndex: index + 1 };
}

/** Parses CLI arguments into validated generator options. */
export function parseModuleArgs(args: readonly string[]): ResolvedModuleOptions {
  let name: string | undefined;
  let scope: string | undefined;
  let out = "modules";
  let crud = false;
  let events = false;
  let audit = false;
  let force = false;
  const seen = new Set<string>();

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === undefined) {
      break;
    }

    if (arg === "--crud" || arg === "--events" || arg === "--audit" || arg === "--force") {
      if (seen.has(arg)) {
        throw new GenerationError(`duplicate argument "${arg}"`);
      }
      seen.add(arg);
      if (arg === "--crud") crud = true;
      if (arg === "--events") events = true;
      if (arg === "--audit") audit = true;
      if (arg === "--force") force = true;
      continue;
    }

    const valueFlags = ["--name", "--scope", "--out"] as const;
    const flag = valueFlags.find(
      (candidate) => arg === candidate || arg.startsWith(`${candidate}=`),
    );
    if (flag === undefined) {
      throw new GenerationError(`unknown argument "${arg}"`);
    }
    if (seen.has(flag)) {
      throw new GenerationError(`duplicate argument "${flag}"`);
    }
    seen.add(flag);

    const prefix = `${flag}=`;
    const inlineValue = arg.startsWith(prefix) ? arg.slice(prefix.length) : undefined;
    const result = readOptionValue(args, index, flag, inlineValue);
    index = result.nextIndex;
    if (flag === "--name") name = result.value;
    if (flag === "--scope") scope = result.value;
    if (flag === "--out") out = result.value;
  }

  if (name === undefined) {
    throw new GenerationError("missing required --name");
  }
  if (scope === undefined) {
    throw new GenerationError("missing required --scope (global, user, or tenant)");
  }

  return validateModuleOptions({
    name,
    scope: scope as ModuleScope,
    crud,
    events,
    audit,
    out,
    force,
  });
}

function dedent(source: string): string {
  const lines = source.trim().split("\n");
  const generatorIndent = " ".repeat(4);
  const result = lines
    .map((line) => (line.startsWith(generatorIndent) ? line.slice(generatorIndent.length) : line))
    .map((line) => line.trimEnd())
    .join("\n");
  return result.replace(/\n{3,}/g, "\n\n");
}

function generated(source: string): string {
  return `${GENERATED_MARKER}\n${CUSTOMIZATION_NOTE}\n\n${dedent(source)}\n`;
}

function indentBlock(source: string, spaces: number): string {
  const prefix = " ".repeat(spaces);
  return source
    .split("\n")
    .map((line) => (line.trim().length === 0 ? line : `${prefix}${line}`))
    .join("\n");
}

function scopeField(scope: ModuleScope): "organizationId" | "userId" | undefined {
  if (scope === "tenant") return "organizationId";
  if (scope === "user") return "userId";
  return undefined;
}

function scopeEntityLine(scope: ModuleScope): string {
  const field = scopeField(scope);
  return field === undefined ? "" : `  ${field}: string;\n`;
}

function domainEntitySource(name: string, scope: ModuleScope): string {
  const pascal = toPascalCase(name);
  return generated(`
    import { ${pascal}InvalidError } from "./${name}.errors";

    export interface ${pascal} {
      id: string;
    ${scopeEntityLine(scope)}  title: string;
      body: string;
      createdAt: Date;
      updatedAt: Date;
    }

    export function assertValid${pascal}Title(title: string): void {
      if (title.trim() === "") {
        throw new ${pascal}InvalidError("title must not be blank");
      }
    }
  `);
}

function domainErrorsSource(name: string): string {
  const pascal = toPascalCase(name);
  return generated(`
    export class ${pascal}NotFoundError extends Error {
      constructor(id: string) {
        super(\`${pascal} not found: \${id}\`);
        this.name = "${pascal}NotFoundError";
      }
    }

    export class ${pascal}InvalidError extends Error {
      constructor(message: string) {
        super(message);
        this.name = "${pascal}InvalidError";
      }
    }
  `);
}

function domainEventsSource(name: string): string {
  const pascal = toPascalCase(name);
  return generated(`
    import { randomUUID } from "node:crypto";

    import type { ${pascal} } from "./${name}.entity";

    export interface ${pascal}Created {
      id: string;
      type: "${name}.created";
      resource: ${pascal};
      actorUserId?: string;
      occurredAt: Date;
    }

    export interface ${pascal}Updated {
      id: string;
      type: "${name}.updated";
      resource: ${pascal};
      actorUserId?: string;
      occurredAt: Date;
    }

    export type ${pascal}Event = ${pascal}Created | ${pascal}Updated;

    export function create${pascal}Event(
      type: "created" | "updated",
      resource: ${pascal},
      actorUserId?: string,
    ): ${pascal}Event {
      const base = { id: randomUUID(), resource, occurredAt: new Date() };
      if (actorUserId === undefined) {
        return type === "created"
          ? { ...base, type: "${name}.created" }
          : { ...base, type: "${name}.updated" };
      }
      return type === "created"
        ? { ...base, type: "${name}.created", actorUserId }
        : { ...base, type: "${name}.updated", actorUserId };
    }
  `);
}

function applicationPortsSource(name: string, scope: ModuleScope, crud: boolean): string {
  const pascal = toPascalCase(name);
  const field = scopeField(scope);
  const scopedField = field === undefined ? "" : `  ${field}: string;\n`;
  const findArgument =
    field === undefined ? "id: string" : `input: { ${field}: string; id: string }`;
  const listArgument = field === undefined ? "" : `${field}: string`;
  const updateInterface = crud
    ? `
    export interface Update${pascal}Input {
    ${scopedField}  id: string;
      title?: string;
      body?: string;
    }
  `
    : "";
  const createInterface = crud
    ? `
    export interface Create${pascal}Input {
    ${scopedField}  title: string;
      body: string;
    }
  `
    : "";
  const crudMethods = crud
    ? `
      create(input: Create${pascal}Input): Promise<${pascal}>;
      update(input: Update${pascal}Input): Promise<${pascal}>;
      delete(${findArgument}): Promise<void>;
    `
    : "";
  return generated(`
    import type { ${pascal} } from "../domain/${name}.entity";

    ${createInterface}${updateInterface}
    export interface ${pascal}Repository {
    ${crudMethods}  findById(${findArgument}): Promise<${pascal} | null>;
      list(${listArgument}): Promise<${pascal}[]>;
    }
  `);
}

function serviceScopeLines(scope: ModuleScope, includeActor = true): string {
  const field = scopeField(scope);
  const scopeLine = field === undefined ? "" : `  ${field}: string;\n`;
  if (!includeActor) return scopeLine;
  return `${scopeLine}  actorUserId${field === undefined ? "?" : ""}: string;\n`;
}

function serviceFindArgument(scope: ModuleScope): string {
  const field = scopeField(scope);
  return field === undefined ? "input.id" : `{ ${field}: input.${field}, id: input.id }`;
}

function serviceListArgument(scope: ModuleScope): string {
  const field = scopeField(scope);
  return field === undefined ? "" : `input.${field}`;
}

function serviceCreateArgument(scope: ModuleScope): string {
  const field = scopeField(scope);
  const scopeLine = field === undefined ? "" : `          ${field}: input.${field},\n`;
  return `{
    ${scopeLine}          title: input.title,
          body: input.body,
        }`;
}

function serviceUpdateArgument(scope: ModuleScope): string {
  const field = scopeField(scope);
  const scopeLine = field === undefined ? "" : `          ${field}: input.${field},\n`;
  return `{
    ${scopeLine}          id: input.id,
          ...(input.title === undefined ? {} : { title: input.title }),
          ...(input.body === undefined ? {} : { body: input.body }),
        }`;
}

function serviceDeleteArgument(scope: ModuleScope): string {
  const field = scopeField(scope);
  return field === undefined ? "input.id" : `{ ${field}: input.${field}, id: input.id }`;
}

function applicationServiceSource(
  name: string,
  scope: ModuleScope,
  crud: boolean,
  events: boolean,
  audit: boolean,
): string {
  const pascal = toPascalCase(name);
  const field = scopeField(scope);
  const actorType = field === undefined ? "string | undefined" : "string";
  const eventImports = events
    ? crud
      ? `import { create${pascal}Event, type ${pascal}Event } from "../domain/${name}.events";`
      : `import type { ${pascal}Event } from "../domain/${name}.events";`
    : "";
  const auditImport = audit ? 'import type { AuditLogger } from "@consulting/audit";' : "";
  const validationImport = crud
    ? `import { assertValid${pascal}Title, type ${pascal} } from "../domain/${name}.entity";`
    : `import type { ${pascal} } from "../domain/${name}.entity";`;
  const auditDep = audit ? "\n      audit?: AuditLogger;" : "";
  const eventsDep = events ? `\n      events?: ${pascal}EventPublisher;` : "";
  const auditHelper =
    audit && crud
      ? `
    async function recordAudit(
      action: "created" | "updated" | "deleted",
      value: ${pascal},
      actorUserId: ${actorType},
    ): Promise<void> {
      if (deps.audit === undefined) return;
      try {
        const actor = actorUserId === undefined ? {} : { actorUserId };
        await deps.audit.record({
          ...actor,
          action: \`${name}.\${action}\`,
          resourceType: "${name}",
          resourceId: value.id,
          outcome: "success",
        });
      } catch {
        // Audit is best-effort and must not change the business result.
      }
    }
  `
      : "";
  const createMethod = crud
    ? `
        async create(input: Create${pascal}ServiceInput): Promise<${pascal}> {
          assertValid${pascal}Title(input.title);
          const value = await deps.repository.create(${serviceCreateArgument(scope)});
          ${events ? `await deps.events?.publish(create${pascal}Event("created", value, input.actorUserId));` : ""}
          ${audit ? `await recordAudit("created", value, input.actorUserId);` : ""}
          return value;
        },
      `
    : "";
  const updateMethod = crud
    ? `
        async update(input: Update${pascal}ServiceInput): Promise<${pascal}> {
          if (input.title !== undefined) {
            assertValid${pascal}Title(input.title);
          }
          const value = await deps.repository.update(${serviceUpdateArgument(scope)});
          ${events ? `await deps.events?.publish(create${pascal}Event("updated", value, input.actorUserId));` : ""}
          ${audit ? `await recordAudit("updated", value, input.actorUserId);` : ""}
          return value;
        },
      `
    : "";
  const deleteMethod = crud
    ? `
        async delete(input: Delete${pascal}ServiceInput): Promise<void> {
          const existing = await deps.repository.findById(${serviceFindArgument(scope)});
          if (existing === null) {
            throw new ${pascal}NotFoundError(input.id);
          }
          await deps.repository.delete(${serviceDeleteArgument(scope)});
          ${audit ? `await recordAudit("deleted", existing, input.actorUserId);` : ""}
        },
      `
    : "";
  const createInput = crud
    ? `
    export interface Create${pascal}ServiceInput {
    ${serviceScopeLines(scope)}  title: string;
      body: string;
    }
  `
    : "";
  const updateInput = crud
    ? `
    export interface Update${pascal}ServiceInput {
    ${serviceScopeLines(scope)}  id: string;
      title?: string;
      body?: string;
    }
  `
    : "";
  const deleteInput = crud
    ? `
    export interface Delete${pascal}ServiceInput {
    ${serviceScopeLines(scope)}  id: string;
    }
  `
    : "";
  const eventPublisher = events
    ? `
    export interface ${pascal}EventPublisher {
      publish(event: ${pascal}Event): Promise<void>;
    }
  `
    : "";
  return generated(`
    ${auditImport}
    ${validationImport}
    import { ${pascal}NotFoundError } from "../domain/${name}.errors";
    ${eventImports}
    import type { ${pascal}Repository } from "./ports";

    ${createInput}${updateInput}${deleteInput}${eventPublisher}
    export interface ${pascal}ServiceDeps {
      repository: ${pascal}Repository;${auditDep}${eventsDep}
    }

    export function create${pascal}Service(deps: ${pascal}ServiceDeps) {
    ${indentBlock(auditHelper, 2)}
      return {
        async findById(input: Find${pascal}ServiceInput): Promise<${pascal}> {
          const value = await deps.repository.findById(${serviceFindArgument(scope)});
          if (value === null) {
            throw new ${pascal}NotFoundError(input.id);
          }
          return value;
        },
        async list(${field === undefined ? "_input" : "input"}: List${pascal}ServiceInput): Promise<${pascal}[]> {
          return deps.repository.list(${serviceListArgument(scope)});
        },${createMethod}${updateMethod}${deleteMethod}
      };
    }

    export interface Find${pascal}ServiceInput {
    ${serviceScopeLines(scope)}  id: string;
    }

    export interface List${pascal}ServiceInput {
    ${serviceScopeLines(scope)}
    }
  `);
}

function infrastructureDbSource(name: string): string {
  const table = toCamelCase(name);
  return generated(`
    import type { ExtractTablesWithRelations } from "drizzle-orm";
    import type { PgTransaction } from "drizzle-orm/pg-core";
    import {
      drizzle,
      type PostgresJsDatabase,
      type PostgresJsQueryResultHKT,
    } from "drizzle-orm/postgres-js";
    import postgres, { type Sql } from "postgres";

    import { ${table} } from "./${name}.schema";

    export const schema = { ${table} };
    export type Db = PostgresJsDatabase<typeof schema>;
    export type DbTransaction = PgTransaction<
      PostgresJsQueryResultHKT,
      typeof schema,
      ExtractTablesWithRelations<typeof schema>
    >;
    export type DbOrTransaction = Db | DbTransaction;

    export function createClient(databaseUrl: string): Sql {
      return postgres(databaseUrl, { max: 1 });
    }

    export function createDb(client: Sql): Db {
      return drizzle(client, { schema });
    }
  `);
}

function infrastructureSchemaSource(name: string, scope: ModuleScope): string {
  const table = toCamelCase(name);
  const tableName = tableNameFor(name);
  const field = scopeField(scope);
  const scopeColumn =
    field === "organizationId"
      ? `
        // TODO: Wire this column to the consuming project's organizations.id foreign key.
        organizationId: uuid("organization_id").notNull(),
      `
      : field === "userId"
        ? `
        userId: text("user_id").notNull(),
      `
        : "";
  const checkName = `${tableName}_title_not_blank`;
  return generated(`
    import { sql } from "drizzle-orm";
    import { check, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

    export const ${table} = pgTable(
      "${tableName}",
      {
        id: uuid("id").primaryKey().defaultRandom(),${scopeColumn}
        title: text("title").notNull(),
        body: text("body").notNull(),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
      },
      (table) => [check("${checkName}", sql\`length(btrim(\${table.title})) > 0\`)],
    );
  `);
}

function infrastructureMapperSource(name: string, scope: ModuleScope): string {
  const pascal = toPascalCase(name);
  const table = toCamelCase(name);
  const field = scopeField(scope);
  const entityScope = field === undefined ? "" : `    ${field}: row.${field},\n`;
  const insertScope = field === undefined ? "" : `    ${field}: input.${field},\n`;
  return generated(`
    import type { Create${pascal}Input, Update${pascal}Input } from "../application/ports";
    import type { ${pascal} } from "../domain/${name}.entity";
    import type { ${table} } from "./${name}.schema";

    export type ${pascal}Row = typeof ${table}.$inferSelect;

    export function rowToEntity(row: ${pascal}Row): ${pascal} {
      return {
        id: row.id,
    ${entityScope}        title: row.title,
        body: row.body,
        createdAt: row.createdAt,
        updatedAt: row.updatedAt,
      };
    }

    export function createToRow(input: Create${pascal}Input): typeof ${table}.$inferInsert {
      return {
    ${insertScope}        title: input.title,
        body: input.body,
      };
    }

    export function updateToRow(input: Update${pascal}Input): Partial<typeof ${table}.$inferInsert> {
      return {
        ...(input.title === undefined ? {} : { title: input.title }),
        ...(input.body === undefined ? {} : { body: input.body }),
        updatedAt: new Date(),
      };
    }
  `);
}

function infrastructureRepositorySource(name: string, scope: ModuleScope): string {
  const pascal = toPascalCase(name);
  const table = toCamelCase(name);
  const field = scopeField(scope);
  const imports =
    field === undefined
      ? 'import { eq } from "drizzle-orm";'
      : 'import { and, eq } from "drizzle-orm";';
  const findWhere =
    field === undefined
      ? `eq(${table}.id, id)`
      : `and(eq(${table}.${field}, input.${field}), eq(${table}.id, input.id))`;
  const updateWhere =
    field === undefined
      ? `eq(${table}.id, input.id)`
      : `and(eq(${table}.${field}, input.${field}), eq(${table}.id, input.id))`;
  const deleteWhere =
    field === undefined
      ? `eq(${table}.id, id)`
      : `and(eq(${table}.${field}, input.${field}), eq(${table}.id, input.id))`;
  const findArgument =
    field === undefined ? "id: string" : "input: { organizationId: string; id: string }";
  const findArgumentForSource =
    field === "userId" ? "input: { userId: string; id: string }" : findArgument;
  const listMethod =
    field === undefined
      ? `
        async list(): Promise<${pascal}[]> {
          const rows = await db.select().from(${table}).orderBy(${table}.createdAt, ${table}.id);
          return rows.map(rowToEntity);
        },`
      : `
        async list(${field}: string): Promise<${pascal}[]> {
          const rows = await db
            .select()
            .from(${table})
            .where(eq(${table}.${field}, ${field}))
            .orderBy(${table}.createdAt, ${table}.id);
          return rows.map(rowToEntity);
        },`;
  const updateInput = `input: Update${pascal}Input`;
  const deleteInput =
    field === undefined ? "id: string" : `input: { ${field}: string; id: string }`;
  return generated(`
    ${imports}

    import type {
      Create${pascal}Input,
      ${pascal}Repository,
      Update${pascal}Input,
    } from "../application/ports";
    import type { ${pascal} } from "../domain/${name}.entity";
    import { ${pascal}NotFoundError } from "../domain/${name}.errors";
    import type { DbOrTransaction } from "./db";
    import { createToRow, rowToEntity, updateToRow } from "./${name}.mapper";
    import { ${table} } from "./${name}.schema";

    export function create${pascal}Repository(db: DbOrTransaction): ${pascal}Repository {
      return {
        async create(input: Create${pascal}Input): Promise<${pascal}> {
          const [row] = await db.insert(${table}).values(createToRow(input)).returning();
          if (row === undefined) {
            throw new Error("insert returned no rows");
          }
          return rowToEntity(row);
        },
        async findById(${field === undefined ? "id: string" : findArgumentForSource}): Promise<${pascal} | null> {
          const [row] = await db.select().from(${table}).where(${findWhere});
          return row === undefined ? null : rowToEntity(row);
        },${listMethod}
        async update(${updateInput}): Promise<${pascal}> {
          const [row] = await db
            .update(${table})
            .set(updateToRow(input))
            .where(${updateWhere})
            .returning();
          if (row === undefined) {
            throw new ${pascal}NotFoundError(input.id);
          }
          return rowToEntity(row);
        },
        async delete(${deleteInput}): Promise<void> {
          await db.delete(${table}).where(${deleteWhere});
        },
      };
    }
  `);
}

function httpSchemasSource(name: string, scope: ModuleScope): string {
  const pascal = toPascalCase(name);
  const field = scopeField(scope);
  const responseScope = field === undefined ? "" : `  ${field}: z.string().min(1),\n`;
  return generated(`
    import { z } from "zod";

    export const Create${pascal}Body = z.object({
      title: z.string().min(1),
      body: z.string(),
    });

    export const Update${pascal}Body = z.object({
      title: z.string().min(1).optional(),
      body: z.string().optional(),
    });

    export const ${pascal}Response = z.object({
      id: z.string().min(1),
    ${responseScope}  title: z.string(),
      body: z.string(),
      createdAt: z.string(),
      updatedAt: z.string(),
    });
    export type ${pascal}Response = z.infer<typeof ${pascal}Response>;
  `);
}

function routeScopeSource(scope: ModuleScope): string {
  if (scope === "tenant") {
    return `
    function scopeFromRequest(c: Context): { organizationId: string; actorUserId: string } {
      return {
        organizationId: requiredHeader(c, "x-organization-id"),
        actorUserId: requiredHeader(c, "x-user-id"),
      };
    }
  `;
  }
  if (scope === "user") {
    return `
    function scopeFromRequest(c: Context): { userId: string; actorUserId: string } {
      return {
        userId: requiredHeader(c, "x-user-id"),
        actorUserId: requiredHeader(c, "x-actor-user-id"),
      };
    }
  `;
  }
  return `
    function scopeFromRequest(c: Context): { actorUserId?: string } {
      const actorUserId = c.req.header("x-user-id");
      return actorUserId === undefined ? {} : { actorUserId };
    }
  `;
}

function httpRoutesSource(name: string, scope: ModuleScope): string {
  const pascal = toPascalCase(name);
  const field = scopeField(scope);
  const tenantComment =
    scope === "tenant"
      ? `
    // Mount this router only after the @consulting/module-organizations tenant middleware.
    // The consuming app must populate x-organization-id and x-user-id from its tenant context.
  `
      : "";
  const requiredHeader =
    scope === "global"
      ? ""
      : `
    function requiredHeader(c: Context, name: string): string {
      const value = c.req.header(name);
      if (value === undefined || value.trim() === "") {
        throw new HTTPException(400, { message: \`Missing required header: \${name}\` });
      }
      return value;
    }
  `;
  const responseScope = field === undefined ? "" : `      ${field}: value.${field},\n`;
  const bodyRoute = `
    app.post(
      "/${name}",
      describeRoute({
        description: "Creates a ${name} resource",
        responses: {
          201: {
            description: "Resource created",
            content: { "application/json": { schema: resolver(${pascal}Response) } },
          },
          400: { description: "Validation failed", content: problem },
        },
      }),
      sValidator("json", Create${pascal}Body, validationErrorHandler),
      async (c) => {
        const input = c.req.valid("json");
        const scope = scopeFromRequest(c);
        const value = await service.create({ ...scope, title: input.title, body: input.body });
        return c.json(toResponse(value), 201);
      },
    );
  `;
  const getRoute = `
    app.get(
      "/${name}/:id",
      describeRoute({
        description: "Gets one ${name} resource",
        responses: {
          200: {
            description: "Resource found",
            content: { "application/json": { schema: resolver(${pascal}Response) } },
          },
          404: { description: "Resource not found", content: problem },
        },
      }),
      async (c) => {
        const scope = scopeFromRequest(c);
        const value = await service.findById({ ...scope, id: c.req.param("id") as string });
        return c.json(toResponse(value), 200);
      },
    );
  `;
  const listRoute = `
    app.get(
      "/${name}",
      describeRoute({
        description: "Lists ${name} resources in the current scope",
        responses: {
          200: {
            description: "Resources listed",
            content: { "application/json": { schema: resolver(z.array(${pascal}Response)) } },
          },
        },
      }),
      async (c) => {
        const values = await service.list(scopeFromRequest(c));
        return c.json(values.map(toResponse), 200);
      },
    );
  `;
  const updateRoute = `
    app.patch(
      "/${name}/:id",
      describeRoute({
        description: "Updates one ${name} resource",
        responses: {
          200: {
            description: "Resource updated",
            content: { "application/json": { schema: resolver(${pascal}Response) } },
          },
          400: { description: "Validation failed", content: problem },
          404: { description: "Resource not found", content: problem },
        },
      }),
      sValidator("json", Update${pascal}Body, validationErrorHandler),
      async (c) => {
        const input = c.req.valid("json");
        const scope = scopeFromRequest(c);
        const value = await service.update({
          ...scope,
          id: c.req.param("id") as string,
          ...(input.title === undefined ? {} : { title: input.title }),
          ...(input.body === undefined ? {} : { body: input.body }),
        });
        return c.json(toResponse(value), 200);
      },
    );
  `;
  const deleteRoute = `
    app.delete(
      "/${name}/:id",
      describeRoute({
        description: "Deletes one ${name} resource",
        responses: {
          204: { description: "Resource deleted" },
          404: { description: "Resource not found", content: problem },
        },
      }),
      async (c) => {
        const scope = scopeFromRequest(c);
        await service.delete({ ...scope, id: c.req.param("id") as string });
        return c.body(null, 204);
      },
    );
  `;
  return generated(`
    import { ProblemDetailsSchema } from "@consulting/contracts";
    import { buildProblemDetails, mapValidationIssues, type ValidationIssue } from "@consulting/core";
    import { sValidator } from "@hono/standard-validator";
    import type { Context } from "hono";
    import { Hono } from "hono";
    ${scope === "global" ? "" : 'import { HTTPException } from "hono/http-exception";'}
    import { describeRoute, resolver } from "hono-openapi";
    import { z } from "zod";

    import { create${pascal}Service, type ${pascal}ServiceDeps } from "../application/${name}-service";
    import type { ${pascal} } from "../domain/${name}.entity";
    import {
      Create${pascal}Body,
      ${pascal}Response,
      type ${pascal}Response as ${pascal}ResponseType,
      Update${pascal}Body,
    } from "./schemas";

    ${tenantComment}
    const PROBLEM_JSON = { "content-type": "application/problem+json" } as const;
    const problem = { "application/problem+json": { schema: resolver(ProblemDetailsSchema) } };

    function validationErrorHandler(
      result: { success: true } | { success: false; error: readonly ValidationIssue[] },
      c: Context,
    ): Response | undefined {
      if (result.success) return undefined;
      return c.json(
        buildProblemDetails({
          status: 400,
          code: "VALIDATION_FAILED",
          errors: mapValidationIssues(result.error),
          requestId: c.get("requestId"),
          instance: c.req.path,
        }),
        400,
        PROBLEM_JSON,
      );
    }

    function toResponse(value: ${pascal}): ${pascal}ResponseType {
      return {
        id: value.id,
    ${responseScope}    title: value.title,
        body: value.body,
        createdAt: value.createdAt.toISOString(),
        updatedAt: value.updatedAt.toISOString(),
      };
    }

    ${requiredHeader}${routeScopeSource(scope)}
    export function create${pascal}Routes(deps: ${pascal}ServiceDeps): Hono {
      const app = new Hono();
      const service = create${pascal}Service(deps);
    ${indentBlock(bodyRoute, 2)}${indentBlock(getRoute, 2)}${indentBlock(listRoute, 2)}${indentBlock(updateRoute, 2)}${indentBlock(deleteRoute, 2)}
      return app;
    }
  `);
}

function testScopeValue(scope: ModuleScope): string {
  if (scope === "tenant") return 'organizationId: "org-1"';
  if (scope === "user") return 'userId: "user-1"';
  return "";
}

function testScopeInput(scope: ModuleScope, idExpression: string): string {
  const scopeValue = testScopeValue(scope);
  const actor = 'actorUserId: "actor-1"';
  return scopeValue === ""
    ? `{ id: ${idExpression}, ${actor} }`
    : `{ ${scopeValue}, ${actor}, id: ${idExpression} }`;
}

function testCreateInput(scope: ModuleScope, title: string, body: string): string {
  const scopeValue = testScopeValue(scope);
  return scopeValue === ""
    ? `{ title: "${title}", body: "${body}", actorUserId: "actor-1" }`
    : `{ ${scopeValue}, title: "${title}", body: "${body}", actorUserId: "actor-1" }`;
}

function fakeRepositorySource(name: string, scope: ModuleScope, crud: boolean): string {
  const pascal = toPascalCase(name);
  const field = scopeField(scope);
  const interpolationStart = "$" + "{";
  const scopeEntityLine =
    field === undefined
      ? ""
      : `    ${field}: ${field === "organizationId" ? '"org-1"' : '"user-1"'},\n`;
  const keyFunction =
    field === undefined
      ? `
    function key(id: string): string {
      return id;
    }
  `
      : `
    function key(scope: string, id: string): string {
      return \`${interpolationStart}scope}:${interpolationStart}id}\`;
    }
  `;
  const initialKey = field === undefined ? "key(initial.id)" : `key(initial.${field}, initial.id)`;
  const createMethod = crud
    ? `
        async create(input: Create${pascal}Input): Promise<${pascal}> {
          const value = makeEntity({
            id: "created-id",
    ${field === undefined ? "" : `        ${field}: input.${field},\n`}        title: input.title,
            body: input.body,
          });
          records.set(${field === undefined ? "key(value.id)" : `key(value.${field}, value.id)`}, value);
          return value;
        },
      `
    : "";
  const updateMethod = crud
    ? `
        async update(input: Update${pascal}Input): Promise<${pascal}> {
          const current = records.get(${field === undefined ? "key(input.id)" : `key(input.${field}, input.id)`});
          if (current === undefined) throw new Error("missing fake record");
          const value = {
            ...current,
            ...(input.title === undefined ? {} : { title: input.title }),
            ...(input.body === undefined ? {} : { body: input.body }),
            updatedAt: new Date(),
          };
          records.set(${field === undefined ? "key(value.id)" : `key(value.${field}, value.id)`}, value);
          return value;
        },
      `
    : "";
  const deleteMethod = crud
    ? `
        async delete(${field === undefined ? "id: string" : `input: { ${field}: string; id: string }`}): Promise<void> {
          records.delete(${field === undefined ? "key(id)" : `key(input.${field}, input.id)`});
        },
      `
    : "";
  const findMethod =
    field === undefined
      ? `
        async findById(id: string): Promise<${pascal} | null> {
          return records.get(key(id)) ?? null;
        },`
      : `
        async findById(input: { ${field}: string; id: string }): Promise<${pascal} | null> {
          return records.get(key(input.${field}, input.id)) ?? null;
        },`;
  const listMethod =
    field === undefined
      ? `
        async list(): Promise<${pascal}[]> {
          return [...records.values()];
        },`
      : `
        async list(${field}: string): Promise<${pascal}[]> {
          return [...records.values()].filter((value) => value.${field} === ${field});
        },`;
  return dedent(`
    function makeEntity(overrides: Partial<${pascal}> = {}): ${pascal} {
      const now = new Date("2026-01-01T00:00:00.000Z");
      return {
        id: "id-1",
    ${scopeEntityLine}    title: "Initial title",
        body: "Initial body",
        createdAt: now,
        updatedAt: now,
        ...overrides,
      };
    }

    ${keyFunction}
    export function createRepository(): ${pascal}Repository {
      const initial = makeEntity();
      const records = new Map<string, ${pascal}>([[${initialKey}, initial]]);
      return {
    ${createMethod}${findMethod}${listMethod}${updateMethod}${deleteMethod}
      };
    }
  `);
}

function generatedTestsSource(
  name: string,
  scope: ModuleScope,
  crud: boolean,
  events: boolean,
  audit: boolean,
): string {
  const pascal = toPascalCase(name);
  const field = scopeField(scope);
  const interpolationStart = "$" + "{";
  const fakeImports = crud
    ? `import type { Create${pascal}Input, ${pascal}Repository, Update${pascal}Input } from "../src/application/ports";`
    : `import type { ${pascal}Repository } from "../src/application/ports";`;
  const eventImport = events
    ? `import { create${pascal}Event, type ${pascal}Event } from "../src/domain/${name}.events";`
    : "";
  const notFoundImport = crud ? `, ${pascal}NotFoundError` : "";
  const fakeSource = fakeRepositorySource(name, scope, crud);
  const scopeAssertion =
    field === undefined
      ? ""
      : `
      expect(value.${field}).toBe(${field === "organizationId" ? '"org-1"' : '"user-1"'});
    `;
  const readInput = testScopeInput(scope, '"id-1"');
  const createInput = testCreateInput(scope, "Created title", "Created body");
  const updateInput = (idExpression: string): string => {
    const scopeValue = testScopeValue(scope);
    return scopeValue === ""
      ? `{ id: ${idExpression}, actorUserId: "actor-1", title: "Updated title" }`
      : `{ ${scopeValue}, id: ${idExpression}, actorUserId: "actor-1", title: "Updated title" }`;
  };
  const crudTest = crud
    ? `
    test("supports CRUD operations through an in-memory repository", async () => {
      const service = create${pascal}Service({ repository: createRepository() });
      const value = await service.create(${createInput});
      expect(value.title).toBe("Created title");
    ${scopeAssertion}
      const read = await service.findById(${testScopeInput(scope, "value.id")});
      expect(read.id).toBe(value.id);
      expect(await service.list(${scope === "global" ? "{}" : `{ ${field}: ${field === "organizationId" ? '"org-1"' : '"user-1"'}, actorUserId: "actor-1" }`})).toHaveLength(2);
      const updated = await service.update(${updateInput("value.id")});
      expect(updated.title).toBe("Updated title");
      await service.delete(${testScopeInput(scope, "value.id")});
      await expect(service.findById(${testScopeInput(scope, "value.id")})).rejects.toBeInstanceOf(
        ${pascal}NotFoundError,
      );
    });
  `
    : "";
  const eventTest = events
    ? `
    test("creates typed domain events", () => {
      const value = makeEntity();
      const created = create${pascal}Event("created", value, "actor-1");
      const updated = create${pascal}Event("updated", value, "actor-1");
      expect(created.type).toBe("${name}.created");
      expect(updated.type).toBe("${name}.updated");
      expect(created.resource.id).toBe(value.id);
    });
  `
    : "";
  const publisherTest =
    events && crud
      ? `
    test("publishes created and updated events", async () => {
      const published: ${pascal}Event[] = [];
      const service = create${pascal}Service({
        repository: createRepository(),
        events: {
          publish: async (event) => {
            published.push(event);
          },
        },
      });
      const value = await service.create(${createInput});
      await service.update(${updateInput("value.id")});
      expect(published.map((event) => event.type)).toEqual([
        "${name}.created",
        "${name}.updated",
      ]);
    });
  `
      : "";
  const auditTest =
    audit && crud
      ? `
    test("records best-effort audit entries for writes", async () => {
      const actions: string[] = [];
      const service = create${pascal}Service({
        repository: createRepository(),
        audit: {
          record: async (entry) => {
            actions.push(\`${interpolationStart}entry.resourceType}:${interpolationStart}entry.action}\`);
          },
          list: async () => [],
        },
      });
      const value = await service.create(${createInput});
      await service.update(${updateInput("value.id")});
      await service.delete(${testScopeInput(scope, "value.id")});
      expect(actions).toEqual([
        "${name}:${name}.created",
        "${name}:${name}.updated",
        "${name}:${name}.deleted",
      ]);
    });
  `
      : "";
  return generated(`
    import { describe, expect, test } from "bun:test";

    ${fakeImports}
    import { create${pascal}Service } from "../src/application/${name}-service";
    import { assertValid${pascal}Title, type ${pascal} } from "../src/domain/${name}.entity";
    import { ${pascal}InvalidError${notFoundImport} } from "../src/domain/${name}.errors";
    ${eventImport}

    ${fakeSource}
    describe("${name} generated module", () => {
      test("rejects blank titles", () => {
        expect(() => assertValid${pascal}Title("  \\t")).toThrow(${pascal}InvalidError);
        expect(() => assertValid${pascal}Title("A valid title")).not.toThrow();
      });

      test("reads through an in-memory repository", async () => {
        const service = create${pascal}Service({ repository: createRepository() });
        const value = await service.findById(${readInput});
        expect(value.id).toBe("id-1");
        expect(await service.list(${scope === "global" ? "{}" : `{ ${field}: ${field === "organizationId" ? '"org-1"' : '"user-1"'}, actorUserId: "actor-1" }`})).toHaveLength(1);
      });
    ${crudTest}${eventTest}${publisherTest}${auditTest}
    });
  `);
}

function packageJsonSource(options: ResolvedModuleOptions): string {
  const dependencies: Record<string, string> = {};
  if (options.audit) dependencies["@consulting/audit"] = "workspace:*";
  if (options.crud) {
    dependencies["@consulting/contracts"] = "workspace:*";
    dependencies["@consulting/core"] = "workspace:*";
    dependencies["@hono/standard-validator"] = "0.2.3";
    dependencies["drizzle-orm"] = "0.45.2";
    dependencies.hono = "4.12.33";
    dependencies["hono-openapi"] = "1.3.1";
    dependencies.postgres = "3.4.9";
    dependencies.zod = "4.4.3";
  }
  const sortedDependencies = Object.fromEntries(
    Object.entries(dependencies).sort(([left], [right]) => left.localeCompare(right)),
  );
  const document = {
    [GENERATED_MARKER]: "Customize this scaffold in a follow-up change; do not edit by hand.",
    name: `@consulting/module-${options.name}`,
    version: "0.1.0",
    private: true,
    type: "module",
    exports: { ".": "./src/index.ts" },
    dependencies: sortedDependencies,
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

function indexSource(options: ResolvedModuleOptions): string {
  const pascal = toPascalCase(options.name);
  const serviceTypes = [
    ...(options.crud ? [`type Create${pascal}ServiceInput`] : []),
    `create${pascal}Service`,
    ...(options.crud ? [`type Delete${pascal}ServiceInput`] : []),
    `type Find${pascal}ServiceInput`,
    `type List${pascal}ServiceInput`,
    ...(options.events ? [`type ${pascal}EventPublisher`] : []),
    `type ${pascal}ServiceDeps`,
    ...(options.crud ? [`type Update${pascal}ServiceInput`] : []),
  ];
  const eventExport = options.events
    ? `
    export {
      create${pascal}Event,
      type ${pascal}Created,
      type ${pascal}Event,
      type ${pascal}Updated,
    } from "./domain/${options.name}.events";
    `
    : "";
  const infrastructureExports = options.crud
    ? `
    export { createClient, createDb } from "./infrastructure/db";
    export { create${pascal}Repository } from "./infrastructure/${options.name}.repository";
    `
    : "";
  return generated(`
    export type {
      ${options.crud ? `Create${pascal}Input, ` : ""}${pascal}Repository${options.crud ? `, Update${pascal}Input` : ""},
    } from "./application/ports";
    export {
      ${serviceTypes.join(",\n      ")},
    } from "./application/${options.name}-service";
    export {
      assertValid${pascal}Title,
      type ${pascal},
    } from "./domain/${options.name}.entity";
    export {
      ${pascal}InvalidError,
      ${pascal}NotFoundError,
    } from "./domain/${options.name}.errors";
    ${eventExport}
    ${options.crud ? `export { create${pascal}Routes } from "./http/${options.name}.routes";` : ""}
    ${infrastructureExports}
  `);
}

function generatedFiles(options: ResolvedModuleOptions): Record<string, string> {
  const files: Record<string, string> = {
    "package.json": packageJsonSource(options),
    "src/index.ts": indexSource(options),
    [`src/domain/${options.name}.entity.ts`]: domainEntitySource(options.name, options.scope),
    [`src/domain/${options.name}.errors.ts`]: domainErrorsSource(options.name),
    "src/application/ports.ts": applicationPortsSource(options.name, options.scope, options.crud),
    [`src/application/${options.name}-service.ts`]: applicationServiceSource(
      options.name,
      options.scope,
      options.crud,
      options.events,
      options.audit,
    ),
    [`tests/${options.name}.test.ts`]: generatedTestsSource(
      options.name,
      options.scope,
      options.crud,
      options.events,
      options.audit,
    ),
  };

  if (options.events) {
    files[`src/domain/${options.name}.events.ts`] = domainEventsSource(options.name);
  }
  if (options.crud) {
    files[`src/http/${options.name}.routes.ts`] = httpRoutesSource(options.name, options.scope);
    files["src/http/schemas.ts"] = httpSchemasSource(options.name, options.scope);
    files["src/infrastructure/db.ts"] = infrastructureDbSource(options.name);
    files[`src/infrastructure/${options.name}.schema.ts`] = infrastructureSchemaSource(
      options.name,
      options.scope,
    );
    files[`src/infrastructure/${options.name}.mapper.ts`] = infrastructureMapperSource(
      options.name,
      options.scope,
    );
    files[`src/infrastructure/${options.name}.repository.ts`] = infrastructureRepositorySource(
      options.name,
      options.scope,
    );
  }
  return files;
}

/** Generates one module and never removes anything outside `<out>/<name>`. */
export function generateModule(options: CreateModuleOptions): ModuleGenerationResult {
  const resolved = validateModuleOptions(options);
  const modulePath = path.resolve(resolved.out, resolved.name);
  if (existsSync(modulePath)) {
    if (!resolved.force) {
      throw new GenerationError(
        `module destination ${modulePath} already exists; pass --force to recreate only this module`,
      );
    }
    rmSync(modulePath, { recursive: true, force: true });
  }

  const files = generatedFiles(resolved);
  for (const [relativePath, source] of Object.entries(files).sort(([left], [right]) =>
    left.localeCompare(right),
  )) {
    const destination = path.join(modulePath, relativePath);
    mkdirSync(path.dirname(destination), { recursive: true });
    writeFileSync(destination, source, "utf8");
  }
  mkdirSync(modulePath, { recursive: true });

  return { modulePath, files: Object.keys(files).sort() };
}

const USAGE = `usage: bun generator/src/create-module.ts --name=<kebab-name> --scope=<global|user|tenant> [--crud] [--events] [--audit] [--out=<parent>] [--force]`;

function main(): void {
  try {
    const result = generateModule(parseModuleArgs(process.argv.slice(2)));
    console.log(`generated ${result.files.length} files in ${result.modulePath}`);
  } catch (error) {
    if (error instanceof GenerationError) {
      console.error(`error: ${error.message}`);
      console.error(USAGE);
      process.exit(1);
    }
    throw error;
  }
}

if (import.meta.main) {
  main();
}
