import type { ProjectPlan } from "./plan";

/**
 * Template selection for files whose composition depends on the feature set.
 *
 * The generator ships TEMPLATE VARIANTS (exact copies of the current source,
 * adapted per feature set) rather than surgical edits: apps/api/src/app.ts
 * and apps/api/src/routes.ts import feature modules (auth, authorization,
 * module-files, module-organizations) that may be physically excluded, so the
 * chosen variant is copied over the destination path. Every template carries
 * a "generated by @consulting/generator — do not edit by hand" marker.
 *
 * Variants live in generator/templates/app/ and MUST be kept in sync with the
 * source composition (the catalog test asserts a template file exists for
 * every selection).
 */
export interface TemplateSelection {
  /** File name under generator/templates/app/ to copy over apps/api/src/app.ts. */
  app: string;
  /** File name under generator/templates/app/ to copy over apps/api/src/routes.ts. */
  routes: string;
}

export function selectTemplates(plan: ProjectPlan): TemplateSelection {
  const app = plan.features.includes("auth")
    ? plan.features.includes("authorization") || plan.features.includes("tenancy")
      ? "app.auth.ts"
      : "app.auth-only.ts"
    : "app.base.ts";
  const routes = plan.features.includes("tenancy")
    ? "routes.tenancy.ts"
    : plan.features.includes("authorization")
      ? "routes.auth.ts"
      : "routes.base.ts";
  return { app, routes };
}
